// LOCALHOST
### Get all employees
GET http://localhost:8080/employees HTTP/1.1


### Get contact by id
GET http://localhost:8080/employees/6720385c1882941b451d4992

### Create contact
POST http://localhost:8080/employees HTTP/1.1
Content-Type: application/json

{
    "FirstName": "Jacob",
    "LastName": "Tester",
    "DoB": "1/20/1998",
    "HireDate": "2/10/2020",
    "Salary": "10000",
    "Job": "123456",
    "Notes": "Test Employee" 
}

### Create contact NULL
POST http://localhost:8080/employees HTTP/1.1
Content-Type: application/json

{
    "FirstName": "null",
    "LastName": "null",
    "DoB": "null",
    "HireDate": "null",
    "Salary": "null",
    "Job": "null",
    "Notes": "null" 
}


### PUT contact
PUT http://localhost:8080/employees/67144fbb6e96302929595209 HTTP/1.1
content-type: application/json

{
    "FirstName": "Jacob",
    "LastName": "Tester",
    "DoB": "1/20/1998",
    "HireDate": "5/26/2024",
    "Salary": "35000",
    "Job": "Tester",
    "Notes": "Test Employee"
}
### DELETE contact
DELETE http://localhost:8080/employees/67203c5c7d3a95607038165f HTTP/1.1

//--------------------------------//

// Production
### Get all employees
GET https://cse341-personalproject-fcdb.onrender.com/employees


### Get contact by id
GET https://cse341-personalproject-fcdb.onrender.com/employees/6653e32ea197540e3ba8f76d


### Create contact
POST https://cse341-personalproject-fcdb.onrender.com/employees HTTP/1.1
Content-Type: application/json

{
    "FirstName": "Jacob","LastName": "Tester","DoB": "1/20/1998","HireDate": "5/26/2024","Salary": "35000","Job": "Tester","Notes": "Test Employee"
}

### Create contact NULL
POST https://cse341-personalproject-fcdb.onrender.com/employees HTTP/1.1
Content-Type: application/json

{
    "firstName": "Jeff",
    "lastName": "Fixer",
    "email": "PutUpdater01@gmail.com",
    "DoB": "1/23/23",
    "HireDate": "5/3/2024",
    "Salary": "60000",
    "Job": "Tester",
    "Notes": "Test PUT Employee"
}


### PUT contact
PUT https://cse341-personalproject-fcdb.onrender.com/employees/671451b3f298e28d62f8baa2 HTTP/1.1
content-type: application/json

{
    "FirstName": "Jacob",
    "LastName": "Tester",
    "DoB": "1/20dfdf",
    "HireDate": "5/26/2024",
    "Salary": "35000",
    "Job": "Tester",
    "Notes": "Test Employee"
}
### DELETE contact
DELETE https://cse341-personalproject-fcdb.onrender.com/employees/665c0bb355a35393f7ee0bd4 HTTP/1.1